language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install lektor"
script: "lektor build"
deploy:
  provider: script
  script: "cat ~/.git/config && lektor deploy ghpages-https"
  on:
    branch: lektor
