language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
before_install:
  - git --version
  - sudo apt-get -qq update
  - sudo apt-get install --only-upgrade -y git-core
  - git --version
install: "pip install lektor"
script: "lektor build"
deploy:
  provider: script
  script: "lektor deploy ghpages-https"
  on:
    branch: lektor
